language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo apt-get install liblo-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest --output-on-failure
